In [6]:
import pandas as pd

df = pd.read_csv('Data/arc.csv')

df = df.drop(['name', 'version', 'name.1'], axis=1)

df.describe()

,wmc,dit,noc,cbo,rfc,lcom,ca,ce,npm,lcom3,...,dam,moa,mfa,cam,ic,cbm,amc,max_cc,avg_cc,bug
count,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,...,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000
mean,9.226496,1.568376,0.162393,7.559829,21.303419,56.158120,2.893162,4.705128,8.572650,1.328542,...,0.543085,0.893162,0.216862,0.483751,0.213675,0.230769,9.746216,2.782051,1.031793,0.141026
std,9.156483,1.102876,1.596441,8.860788,26.423057,138.678483,6.628825,6.490883,8.550096,0.614953,...,0.491475,1.806437,0.387875,0.277221,0.431169,0.488224,10.014414,3.556946,0.724088,0.416124
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,1.000000,0.000000,3.000000,5.250000,1.000000,0.000000,1.000000,3.000000,0.833333,...,0.000000,0.000000,0.000000,0.286255,0.000000,0.000000,3.000000,1.000000,0.714300,0.000000
50%,6.000000,1.000000,0.000000,5.000000,14.000000,6.000000,1.000000,2.000000,5.000000,0.955606,...,1.000000,0.000000,0.000000,0.437500,0.000000,0.000000,6.571429,1.000000,1.000000,0.000000
75%,13.000000,1.000000,0.000000,8.000000,25.000000,53.750000,3.000000,5.000000,12.000000,2.000000,...,1.000000,1.000000,0.000000,0.666667,0.000000,0.000000,14.875000,4.000000,1.262625,0.000000
max,55.000000,5.000000,23.000000,74.000000,166.000000,1417.000000,71.000000,36.000000,55.000000,2.000000,...,1.000000,10.000000,1.000000,1.000000,2.000000,3.000000,49.463415,34.000000,6.000000,2.000000

In [7]:
zeroes = 0
ones = 0

for i in range(len(df['bug'])):
    if df['bug'][i] != 0:  ones += 1
    else: zeroes += 1
    
print('zeros: ', zeroes, ' | Ones: ', ones)

zeros:  207  | Ones:  27

In [8]:
ones*100/zeroes

13.043478260869565